### PR TITLE
Added generic derivation of production Edge URLs for any cloud region

### PR DESCRIPTION
**Pull request by whygoyal**
This PR will fix the derivation of Edge URLs from INT and OS2 CoAP URL. Also added generic derivation from PROD CoAP URL, so it should support all regions - us-east-1, ap-northeast and eu-west-1.

### CODE REVIEW

**Review by mohitsingalarm — APPROVED** [review]
LGTM

**Review by mray190 — APPROVED** [review]

**Comment by mray190** [comment]
@ygoyal18 Good to go! Lets get this merged asap.

Once its merged, I can make a SHA change to `snap-pelion-edge`

**Comment by psppalash** [comment]
@mray190 @ygoyal18  I will test this PR today on a Dell gateway. And if the fix works, we can merge it.

**Comment by psppalash** [comment]
Tested on Dell gateway with OS2 cloud. The fix works. Can see the gateway in the portal and relay-term/log features work as expected.

**Comment by whygoyal** [comment]
Thanks @psppalash. Merging this PR.

**Pull request merged**
