### PR TITLE
Rename info & testnet.sh to edge-info and edge-testnet

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Rename the tools to have some common theme with the names and most importantly - avoid overlap with names - there is already an info tool in the Linux world, so we cannot re-use that name.

## Todos

- [x] Changelog updated
- [x] Run `shellcheck` or `pysh-check` before committing code - no more warnings than earlier (preferrably less)
- [x] Will tag a proper release, if need be.
- [ ] Will update required recipes/builds as well.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
I think I would be favored in having a completely flat structure for this repo. In an ideal world, we would just copy the required files to `/usr/bin` and be done with it.

The extra folders we have here are not really helping. Opinions? @petedyerarm  @jenia81 @x85446

**Review by petedyer11 — CHANGES_REQUESTED** [review]
The github actions are failing as they are hard coded file names.

**Comment by JanneKiiskila** [comment]
Fixed the filenames now.

**Comment by JanneKiiskila** [comment]
The test is still running. It's trying to run edge-info and that somehow mystically [fails](https://github.com/PelionIoT/pe-utils/actions/runs/4882344028/jobs/8712299863) with openBinary not found. 

```
Run shellcheck edge-tool/edge-info
edge-tool/edge-info: edge-tool/edge-info: openBinaryFile: does not exist (No such file or directory)
Error: Process completed with exit code 2.
```

The whole repo does not have openBinary as a reference, anywhere.

```
 14:43 jannek@jannek-P720:/ssd/pe-utils$ git grep openBinaryFile
 15:15 jannek@jannek-P720:/ssd/pe-utils$ git grep -i openBinaryFile
```
We probably need to disable that part of the job and understand better where this thing is coming from (it used to pass earlier).

..And it was just some typos! (Fixed).

**Review by petedyer11 — APPROVED** [review]
LGTM

**Pull request merged**
